# Generated by Django 2.2.7 on 2019-11-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
